services:
  - type: web
    name: audio-visualizer
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
